/*
 * The MIT License
 *
 * Copyright 2021 Vladislav Gorskii.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ru.VladTheMountain.oclide.editor;

import java.io.File;

/**
 *
 * @author VladTheMountain
 */
public class CreateNewProjectDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form createNewProject
     *
     * @param parent
     */
    public CreateNewProjectDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlPanel = new javax.swing.JPanel();
        finishButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        projectTypePanel = new javax.swing.JPanel();
        descriptionPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        categoriesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categorylist = new javax.swing.JList<>();
        projectsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectTypeList = new javax.swing.JList<>();
        projectPropertiesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        projectNameField = new javax.swing.JTextField();
        projectFolderField = new javax.swing.JTextField(new File("projects").getAbsolutePath() + "\\" + projectNameField.getText());
            scriptSeparator = new javax.swing.JSeparator();
            jLabel3 = new javax.swing.JLabel();
            librarySeparator = new javax.swing.JSeparator();
            jLabel4 = new javax.swing.JLabel();
            libraryNameField = new javax.swing.JTextField();
            scriptNameField = new javax.swing.JTextField();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Creating a new project");
            setResizable(false);

            finishButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            finishButton.setText("Finish");
            finishButton.setEnabled(false);
            finishButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    finishButtonActionPerformed(evt);
                }
            });

            nextButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            nextButton.setText("Next >>");
            nextButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    nextButtonActionPerformed(evt);
                }
            });

            previousButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            previousButton.setText("<< Previous");
            previousButton.setEnabled(false);
            previousButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    previousButtonActionPerformed(evt);
                }
            });

            cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            cancelButton.setText("Cancel");
            cancelButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cancelButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
            controlPanel.setLayout(controlPanelLayout);
            controlPanelLayout.setHorizontalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(previousButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nextButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(finishButton)
                    .addContainerGap())
            );
            controlPanelLayout.setVerticalGroup(
                controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(finishButton)
                        .addComponent(nextButton)
                        .addComponent(previousButton)
                        .addComponent(cancelButton))
                    .addContainerGap())
            );

            jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
            jTabbedPane2.setEnabled(false);
            jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

            descriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

            jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

            descriptionText.setEditable(false);
            descriptionText.setColumns(20);
            descriptionText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
            descriptionText.setRows(5);
            descriptionText.setText("Creates a new, blank project.");
            jScrollPane3.setViewportView(descriptionText);

            javax.swing.GroupLayout descriptionPanelLayout = new javax.swing.GroupLayout(descriptionPanel);
            descriptionPanel.setLayout(descriptionPanelLayout);
            descriptionPanelLayout.setHorizontalGroup(
                descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3)
            );
            descriptionPanelLayout.setVerticalGroup(
                descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            );

            categoriesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categories:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

            categorylist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            categorylist.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "OpenComputers" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            categorylist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            categorylist.setSelectedIndex(0);
            jScrollPane1.setViewportView(categorylist);

            javax.swing.GroupLayout categoriesPanelLayout = new javax.swing.GroupLayout(categoriesPanel);
            categoriesPanel.setLayout(categoriesPanelLayout);
            categoriesPanelLayout.setHorizontalGroup(
                categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            );
            categoriesPanelLayout.setVerticalGroup(
                categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            );

            projectsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Projects:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

            projectTypeList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            projectTypeList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = { "Blank Project", "OpenOS Script", "OpenOS Library" };
                public int getSize() { return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            projectTypeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            projectTypeList.setSelectedIndex(0);
            projectTypeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                    projectTypeListValueChanged(evt);
                }
            });
            jScrollPane2.setViewportView(projectTypeList);

            javax.swing.GroupLayout projectsPanelLayout = new javax.swing.GroupLayout(projectsPanel);
            projectsPanel.setLayout(projectsPanelLayout);
            projectsPanelLayout.setHorizontalGroup(
                projectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
            );
            projectsPanelLayout.setVerticalGroup(
                projectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2)
            );

            javax.swing.GroupLayout projectTypePanelLayout = new javax.swing.GroupLayout(projectTypePanel);
            projectTypePanel.setLayout(projectTypePanelLayout);
            projectTypePanelLayout.setHorizontalGroup(
                projectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(projectTypePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(projectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(descriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(projectTypePanelLayout.createSequentialGroup()
                            .addComponent(categoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(projectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            projectTypePanelLayout.setVerticalGroup(
                projectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(projectTypePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(projectTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(categoriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(projectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jTabbedPane2.addTab("Project type", projectTypePanel);

            jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            jLabel1.setText("Project Name:");

            jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            jLabel2.setText("Project Folder:");

            projectNameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            projectNameField.setText("LuaScript1");
            projectNameField.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    projectNameFieldActionPerformed(evt);
                }
            });

            projectFolderField.setEditable(false);
            projectFolderField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

            jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            jLabel3.setText("Script name:");

            jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
            jLabel4.setText("Library name:");

            libraryNameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

            scriptNameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

            javax.swing.GroupLayout projectPropertiesPanelLayout = new javax.swing.GroupLayout(projectPropertiesPanel);
            projectPropertiesPanel.setLayout(projectPropertiesPanelLayout);
            projectPropertiesPanelLayout.setHorizontalGroup(
                projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(projectPropertiesPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scriptSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectPropertiesPanelLayout.createSequentialGroup()
                            .addGroup(projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(projectNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                .addComponent(projectFolderField)))
                        .addComponent(librarySeparator)
                        .addGroup(projectPropertiesPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(scriptNameField))
                        .addGroup(projectPropertiesPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(libraryNameField)))
                    .addContainerGap())
            );
            projectPropertiesPanelLayout.setVerticalGroup(
                projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(projectPropertiesPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(projectFolderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(scriptSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(scriptNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(librarySeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(projectPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(libraryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(210, Short.MAX_VALUE))
            );

            jTabbedPane2.addTab("Project configuration", projectPropertiesPanel);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        this.jTabbedPane2.setSelectedIndex(this.jTabbedPane2.getSelectedIndex() - 1);
        this.previousButton.setEnabled(false);
        this.nextButton.setEnabled(true);
        this.finishButton.setEnabled(false);
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        this.jTabbedPane2.setSelectedIndex(this.jTabbedPane2.getSelectedIndex() + 1);
        this.previousButton.setEnabled(true);
        this.nextButton.setEnabled(false);
        this.finishButton.setEnabled(true);
        switch (this.projectTypeList.getSelectedIndex()) {
            case 0:
            default:
                this.scriptSeparator.setVisible(false);
                this.jLabel3.setVisible(false);
                this.scriptNameField.setVisible(false);
                this.librarySeparator.setVisible(false);
                this.jLabel4.setVisible(false);
                this.libraryNameField.setVisible(false);
                break;
            case 1:
                this.scriptSeparator.setVisible(true);
                this.jLabel3.setVisible(true);
                this.scriptNameField.setVisible(true);
                this.librarySeparator.setVisible(false);
                this.jLabel4.setVisible(false);
                this.libraryNameField.setVisible(false);
                break;
            case 2:
                this.scriptSeparator.setVisible(false);
                this.jLabel3.setVisible(false);
                this.scriptNameField.setVisible(false);
                this.librarySeparator.setVisible(true);
                this.jLabel4.setVisible(true);
                this.libraryNameField.setVisible(true);
                break;
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        MainFrame.createProject(this.projectNameField.getText(), this.projectFolderField.getText());
        this.dispose();
    }//GEN-LAST:event_finishButtonActionPerformed

    private void projectTypeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_projectTypeListValueChanged
        switch (this.projectTypeList.getSelectedIndex()) {
            case 0:
                this.descriptionText.setText("Creates a new, blank project.");
                break;
            case 1:
                this.descriptionText.setText("Creates a new project with /bin/ folder.\nAllows to customize the name of the script.");
                break;
            case 2:
                this.descriptionText.setText("Creates a new project with /lib/ folder.\nAllows to customize the name of the library.");
                break;
        }
    }//GEN-LAST:event_projectTypeListValueChanged

    private void projectNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameFieldActionPerformed
        this.projectFolderField.setText(new File("projects").getAbsolutePath() + "\\" + projectNameField.getText());
    }//GEN-LAST:event_projectNameFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel categoriesPanel;
    private javax.swing.JList<String> categorylist;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField libraryNameField;
    private javax.swing.JSeparator librarySeparator;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField projectFolderField;
    private javax.swing.JTextField projectNameField;
    private javax.swing.JPanel projectPropertiesPanel;
    private javax.swing.JList<String> projectTypeList;
    private javax.swing.JPanel projectTypePanel;
    private javax.swing.JPanel projectsPanel;
    private javax.swing.JTextField scriptNameField;
    private javax.swing.JSeparator scriptSeparator;
    // End of variables declaration//GEN-END:variables
}
