/*
 * The MIT License
 *
 * Copyright 2021 Vladislav Gorskii.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ru.VladTheMountain.oclide.ui.frames;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.nio.file.FileSystems;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.AbstractListModel;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

/**
 *
 * @author VladTheMountain
 */
public class SettingsFrame extends javax.swing.JFrame {

    final ResourceBundle localiztionResource = ResourceBundle.getBundle("ru.VladTheMountain.oclide.resources.dialog.Dialog", Locale.getDefault());
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form SettingsFrame
     */
    public SettingsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingTabs = new JTabbedPane();
        idePanel = new JPanel();
        jLabel1 = new JLabel();
        workingDirTextField = new JTextField();
        jCheckBox1 = new JCheckBox();
        editorPanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        settingList = new JList<>();
        emulatorTabs = new JTabbedPane();
        ocemuPanel = new JPanel();
        jLabel3 = new JLabel();
        ocemuTextField = new JTextField();
        ocbrainPanel = new JPanel();
        brainOutputRedirectionCheckBox = new JCheckBox();
        ocdesktopPanel = new JPanel();
        codePanel = new JPanel();
        jLabel4 = new JLabel();
        aurumPanel = new JPanel();
        jLabel5 = new JLabel();
        ocemulatorPanel = new JPanel();
        environmentTabs = new JTabbedPane();
        envGeneralPanel = new JPanel();
        minecraftPanel = new JPanel();
        jLabel2 = new JLabel();
        minecraftTextField = new JTextField();
        jPanel1 = new JPanel();
        jScrollPane2 = new JScrollPane();
        jList1 = new JList<>();
        jSeparator1 = new JSeparator();
        jScrollPane4 = new JScrollPane();
        jList2 = new JList<>();
        openComputersEnvironment = new JComboBox<>();
        jLabel8 = new JLabel();
        thirdPartyCheckBox = new JCheckBox();
        ocvmPanel = new JPanel();
        jLabel6 = new JLabel();
        opencomputersvmPanel = new JPanel();
        modulesPanel = new JPanel();
        luaPanel = new JPanel();
        jLabel7 = new JLabel();
        luaPathField = new JTextField();
        controlPanel = new JPanel();
        okButton = new JButton();
        cancelButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings (UI PREVIEW MODE)");
        setResizable(false);

        jLabel1.setText("OCLIDE directory:");

        workingDirTextField.setEditable(false);
        workingDirTextField.setText(System.getProperty("user.dir"));

        jCheckBox1.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("UI preview mode (will be disabled in the next update)");
        jCheckBox1.setEnabled(false);

        GroupLayout idePanelLayout = new GroupLayout(idePanel);
        idePanel.setLayout(idePanelLayout);
        idePanelLayout.setHorizontalGroup(idePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, idePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idePanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(idePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(workingDirTextField, GroupLayout.PREFERRED_SIZE, 400, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        idePanelLayout.setVerticalGroup(idePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(idePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(workingDirTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        settingTabs.addTab("IDE", idePanel);

        settingList.setModel(new AbstractListModel<String>() {
            String[] strings = { "Background", "Keywords", "Identifiers", "Functions", "Numbers", "Strings" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        settingList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(settingList);

        GroupLayout editorPanelLayout = new GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(editorPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        editorPanelLayout.setVerticalGroup(editorPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        settingTabs.addTab("Editor", editorPanel);

        jLabel3.setText("Path to OCEmu:");

        ocemuTextField.setEditable(false);
        ocemuTextField.setText(System.getProperty("user.dir") + FileSystems.getDefault().getSeparator() + "OCEmu");

        GroupLayout ocemuPanelLayout = new GroupLayout(ocemuPanel);
        ocemuPanel.setLayout(ocemuPanelLayout);
        ocemuPanelLayout.setHorizontalGroup(ocemuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ocemuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ocemuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(ocemuPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 433, Short.MAX_VALUE))
                    .addComponent(ocemuTextField))
                .addContainerGap())
        );
        ocemuPanelLayout.setVerticalGroup(ocemuPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ocemuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocemuTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        emulatorTabs.addTab("OCEmu", ocemuPanel);

        brainOutputRedirectionCheckBox.setSelected(true);
        brainOutputRedirectionCheckBox.setText("Redirect output to IDE's console");
        brainOutputRedirectionCheckBox.setEnabled(false);

        GroupLayout ocbrainPanelLayout = new GroupLayout(ocbrainPanel);
        ocbrainPanel.setLayout(ocbrainPanelLayout);
        ocbrainPanelLayout.setHorizontalGroup(ocbrainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ocbrainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brainOutputRedirectionCheckBox)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        ocbrainPanelLayout.setVerticalGroup(ocbrainPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ocbrainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brainOutputRedirectionCheckBox)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        emulatorTabs.addTab("Ocelot Brain", ocbrainPanel);

        GroupLayout ocdesktopPanelLayout = new GroupLayout(ocdesktopPanel);
        ocdesktopPanel.setLayout(ocdesktopPanelLayout);
        ocdesktopPanelLayout.setHorizontalGroup(ocdesktopPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        ocdesktopPanelLayout.setVerticalGroup(ocdesktopPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        emulatorTabs.addTab("Ocelot Desktop", ocdesktopPanel);

        jLabel4.setFont(new Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setText("Linux only");

        GroupLayout codePanelLayout = new GroupLayout(codePanel);
        codePanel.setLayout(codePanelLayout);
        codePanelLayout.setHorizontalGroup(codePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(codePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        codePanelLayout.setVerticalGroup(codePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(codePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        emulatorTabs.addTab("CODE", codePanel);

        jLabel5.setFont(new Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setText("Linux only");

        GroupLayout aurumPanelLayout = new GroupLayout(aurumPanel);
        aurumPanel.setLayout(aurumPanelLayout);
        aurumPanelLayout.setHorizontalGroup(aurumPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(aurumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        aurumPanelLayout.setVerticalGroup(aurumPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(aurumPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        emulatorTabs.addTab("Aurum Emulator", aurumPanel);

        GroupLayout ocemulatorPanelLayout = new GroupLayout(ocemulatorPanel);
        ocemulatorPanel.setLayout(ocemulatorPanelLayout);
        ocemulatorPanelLayout.setHorizontalGroup(ocemulatorPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        ocemulatorPanelLayout.setVerticalGroup(ocemulatorPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        emulatorTabs.addTab("OCEmulator", ocemulatorPanel);

        settingTabs.addTab("Emulators", emulatorTabs);

        GroupLayout envGeneralPanelLayout = new GroupLayout(envGeneralPanel);
        envGeneralPanel.setLayout(envGeneralPanelLayout);
        envGeneralPanelLayout.setHorizontalGroup(envGeneralPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        envGeneralPanelLayout.setVerticalGroup(envGeneralPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        environmentTabs.addTab("General", envGeneralPanel);

        jLabel2.setText("Path to .minecraft directory:");

        jPanel1.setBorder(BorderFactory.createTitledBorder(null, "Target machine", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Tahoma", 1, 14))); // NOI18N

        jList1.setBorder(BorderFactory.createTitledBorder(null, "World", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
        jList1.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jSeparator1.setOrientation(SwingConstants.VERTICAL);

        jList2.setBorder(BorderFactory.createTitledBorder(null, "Machine UUID", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));
        jList2.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList2);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jSeparator1, GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        openComputersEnvironment.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Target OpenComputers build:");

        thirdPartyCheckBox.setText("Allow 3rd-party modifications");
        thirdPartyCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                thirdPartyCheckBoxActionPerformed(evt);
            }
        });

        GroupLayout minecraftPanelLayout = new GroupLayout(minecraftPanel);
        minecraftPanel.setLayout(minecraftPanelLayout);
        minecraftPanelLayout.setHorizontalGroup(minecraftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(minecraftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minecraftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(minecraftTextField, GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openComputersEnvironment, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(minecraftPanelLayout.createSequentialGroup()
                        .addGroup(minecraftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(thirdPartyCheckBox, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        minecraftPanelLayout.setVerticalGroup(minecraftPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(minecraftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minecraftTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdPartyCheckBox)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openComputersEnvironment, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        environmentTabs.addTab("Minecraft", minecraftPanel);

        jLabel6.setFont(new Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setText("Linux only");

        GroupLayout ocvmPanelLayout = new GroupLayout(ocvmPanel);
        ocvmPanel.setLayout(ocvmPanelLayout);
        ocvmPanelLayout.setHorizontalGroup(ocvmPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ocvmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        ocvmPanelLayout.setVerticalGroup(ocvmPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(ocvmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        environmentTabs.addTab("OCVM", ocvmPanel);

        GroupLayout opencomputersvmPanelLayout = new GroupLayout(opencomputersvmPanel);
        opencomputersvmPanel.setLayout(opencomputersvmPanelLayout);
        opencomputersvmPanelLayout.setHorizontalGroup(opencomputersvmPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        opencomputersvmPanelLayout.setVerticalGroup(opencomputersvmPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        environmentTabs.addTab("OpenComputers VM", opencomputersvmPanel);

        settingTabs.addTab("Environments", environmentTabs);

        GroupLayout modulesPanelLayout = new GroupLayout(modulesPanel);
        modulesPanel.setLayout(modulesPanelLayout);
        modulesPanelLayout.setHorizontalGroup(modulesPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        modulesPanelLayout.setVerticalGroup(modulesPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        settingTabs.addTab("Modules", modulesPanel);

        jLabel7.setText("Lua path:");

        luaPathField.setText(System.getenv("LUA_PATH").length()<2 ? "LUA_PATH not set in current environment" : System.getenv("LUA_PATH"));

        GroupLayout luaPanelLayout = new GroupLayout(luaPanel);
        luaPanel.setLayout(luaPanelLayout);
        luaPanelLayout.setHorizontalGroup(luaPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(luaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(luaPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(luaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(luaPathField, GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                .addContainerGap())
        );
        luaPanelLayout.setVerticalGroup(luaPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(luaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luaPathField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        settingTabs.addTab("Lua", luaPanel);

        okButton.setText("Apply");
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GroupLayout controlPanelLayout = new GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(controlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(controlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(settingTabs)
            .addComponent(controlPanel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(settingTabs)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void thirdPartyCheckBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_thirdPartyCheckBoxActionPerformed
        if (thirdPartyCheckBox.isSelected()) {
            openComputersEnvironment.addItem("OpenComputers 1.7.5 + Fingercomp's debugger");
            openComputersEnvironment.addItem("OpenComputers 1.7.5 + Fingercomp's profiler");
        } else {
            openComputersEnvironment.removeItem("OpenComputers 1.7.5 + Fingercomp's debugger");
            openComputersEnvironment.removeItem("OpenComputers 1.7.5 + Fingercomp's profiler");
        }
    }//GEN-LAST:event_thirdPartyCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel aurumPanel;
    private JCheckBox brainOutputRedirectionCheckBox;
    private JButton cancelButton;
    private JPanel codePanel;
    private JPanel controlPanel;
    private JPanel editorPanel;
    private JTabbedPane emulatorTabs;
    private JPanel envGeneralPanel;
    private JTabbedPane environmentTabs;
    private JPanel idePanel;
    private JCheckBox jCheckBox1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JList<String> jList1;
    private JList<String> jList2;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane4;
    private JSeparator jSeparator1;
    private JPanel luaPanel;
    private JTextField luaPathField;
    private JPanel minecraftPanel;
    private JTextField minecraftTextField;
    private JPanel modulesPanel;
    private JPanel ocbrainPanel;
    private JPanel ocdesktopPanel;
    private JPanel ocemuPanel;
    private JTextField ocemuTextField;
    private JPanel ocemulatorPanel;
    private JPanel ocvmPanel;
    private JButton okButton;
    private JComboBox<String> openComputersEnvironment;
    private JPanel opencomputersvmPanel;
    private JList<String> settingList;
    private JTabbedPane settingTabs;
    private JCheckBox thirdPartyCheckBox;
    private JTextField workingDirTextField;
    // End of variables declaration//GEN-END:variables
}
