/*
 * The MIT License
 *
 * Copyright 2021 Vladislav Gorskii.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package io.VladTheMountain.oclide.ui.configurators;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;
import io.VladTheMountain.emulator.ui.OcelotEmulatorFrame;

/**
 * Ocelot Desktop by LeshaInc
 *
 * Workspace configurator UI.
 *
 * @author VladTheMountain
 */
public class OcelotDesktopForm extends javax.swing.JFrame {

    final ResourceBundle localiztionResource = ResourceBundle.getBundle("ru.VladTheMountain.oclide.resources.configurator.ocelot.Ocelot", Locale.getDefault());
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form ConfiguratorForm
     */
    public OcelotDesktopForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eepromButtons = new ButtonGroup();
        controlPanel = new JPanel();
        launchButton = new JButton();
        cancelButton = new JButton();
        extensionsPanel = new JPanel();
        architecturePanel = new JPanel();
        eepromPanel = new JPanel();
        luaEEPROMButton = new JRadioButton();
        customEEPROMButton = new JRadioButton();
        customEEPROMField = new JTextField();
        jLabel2 = new JLabel();
        JComboBox<String> floppyComboBox = new JComboBox<>();
        jLabel3 = new JLabel();
        JComboBox<String> caseTierComboBox = new JComboBox<>();
        primaryPanel = new JPanel();
        jLabel1 = new JLabel();
        JComboBox<String> processingUnitComboBox = new JComboBox<>();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        JComboBox<String> memorySlot1ComboBox = new JComboBox<>();
        JComboBox<String> memorySlot2ComboBox = new JComboBox<>();
        secondaryPanel = new JPanel();
        jMenuBar1 = new JMenuBar();
        fileMenu = new JMenu();
        clearConfigItem = new JMenuItem();
        importConfigItem = new JMenuItem();
        saveConfigItem = new JMenuItem();
        jSeparator1 = new JPopupMenu.Separator();
        exitConfigItem = new JMenuItem();
        helpMenu = new JMenu();
        helpItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OCEmu Configuration");
        setAlwaysOnTop(true);

        controlPanel.setBorder(BorderFactory.createEtchedBorder());

        launchButton.setText("Launch Ocelot");
        launchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                launchButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");

        GroupLayout controlPanelLayout = new GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(controlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(launchButton)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(controlPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(launchButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        extensionsPanel.setBorder(BorderFactory.createTitledBorder(null, "Storage", TitledBorder.LEFT, TitledBorder.TOP, new Font("Segoe UI", 1, 14))); // NOI18N
        extensionsPanel.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        extensionsPanel.setMinimumSize(new Dimension(200, 200));

        GroupLayout extensionsPanelLayout = new GroupLayout(extensionsPanel);
        extensionsPanel.setLayout(extensionsPanelLayout);
        extensionsPanelLayout.setHorizontalGroup(extensionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        extensionsPanelLayout.setVerticalGroup(extensionsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        architecturePanel.setBorder(BorderFactory.createTitledBorder(null, "Architecture", TitledBorder.LEFT, TitledBorder.TOP, new Font("Segoe UI", 1, 14))); // NOI18N
        architecturePanel.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        architecturePanel.setMinimumSize(new Dimension(200, 200));

        eepromPanel.setBorder(BorderFactory.createTitledBorder(null, "EEPROM", TitledBorder.LEFT, TitledBorder.TOP, new Font("Segoe UI", 1, 11))); // NOI18N

        eepromButtons.add(luaEEPROMButton);
        luaEEPROMButton.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        luaEEPROMButton.setSelected(true);
        luaEEPROMButton.setText("Lua BIOS");

        eepromButtons.add(customEEPROMButton);
        customEEPROMButton.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        customEEPROMButton.setText(" AdvLoader");

        customEEPROMField.setEditable(false);
        customEEPROMField.setFont(new Font("Monospaced", 0, 10)); // NOI18N
        customEEPROMField.setToolTipText("Path to custom EEPROM script");
        customEEPROMField.setOpaque(false);

        GroupLayout eepromPanelLayout = new GroupLayout(eepromPanel);
        eepromPanel.setLayout(eepromPanelLayout);
        eepromPanelLayout.setHorizontalGroup(eepromPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(customEEPROMField)
            .addComponent(customEEPROMButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(luaEEPROMButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        eepromPanelLayout.setVerticalGroup(eepromPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(eepromPanelLayout.createSequentialGroup()
                .addComponent(luaEEPROMButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customEEPROMButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customEEPROMField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel2.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setLabelFor(floppyComboBox);
        jLabel2.setText("Floppy:");

        floppyComboBox.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        floppyComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "OpenOS", "Plan9k", "OPPM", "OpenLoader", "Network", "OpenIRC", "Data Card Software", "Empty" }));

        jLabel3.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setLabelFor(caseTierComboBox);
        jLabel3.setText("Case type:");
        jLabel3.setToolTipText("");

        caseTierComboBox.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        caseTierComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Case Tier 1", "Case Tier 2", "Case Tier 3", "Case Creative" }));

        GroupLayout architecturePanelLayout = new GroupLayout(architecturePanel);
        architecturePanel.setLayout(architecturePanelLayout);
        architecturePanelLayout.setHorizontalGroup(architecturePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(architecturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(architecturePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(eepromPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(architecturePanelLayout.createSequentialGroup()
                        .addGroup(architecturePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(architecturePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(floppyComboBox, 0, 1, Short.MAX_VALUE)
                            .addComponent(caseTierComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        architecturePanelLayout.setVerticalGroup(architecturePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, architecturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(architecturePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caseTierComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(architecturePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(floppyComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eepromPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        primaryPanel.setBorder(BorderFactory.createTitledBorder(null, "Primary Components", TitledBorder.LEFT, TitledBorder.TOP, new Font("Segoe UI", 1, 14))); // NOI18N
        primaryPanel.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        primaryPanel.setMinimumSize(new Dimension(200, 200));

        jLabel1.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setLabelFor(processingUnitComboBox);
        jLabel1.setText("Processing Unit:");

        processingUnitComboBox.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        processingUnitComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "CPU Tier 1", "CPU Tier 2", "CPU Tier 3", "APU Tier 2", "APU Tier 3", "APU Creative" }));

        jLabel4.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Memory Slot 1:");

        jLabel5.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Memory Slot 2:");

        memorySlot1ComboBox.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        memorySlot1ComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Tier 1", "Tier 1.5", "Tier 2", "Tier 2.5", "Tier 3", "Tier 3.5" }));

        memorySlot2ComboBox.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        memorySlot2ComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Tier 1", "Tier 1.5", "Tier 2", "Tier 2.5", "Tier 3", "Tier 3.5" }));

        GroupLayout primaryPanelLayout = new GroupLayout(primaryPanel);
        primaryPanel.setLayout(primaryPanelLayout);
        primaryPanelLayout.setHorizontalGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(primaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(primaryPanelLayout.createSequentialGroup()
                        .addGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(primaryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(processingUnitComboBox, 0, 1, Short.MAX_VALUE)
                    .addComponent(memorySlot2ComboBox, 0, 95, Short.MAX_VALUE)
                    .addComponent(memorySlot1ComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        primaryPanelLayout.setVerticalGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(primaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(processingUnitComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(memorySlot1ComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(primaryPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(memorySlot2ComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        secondaryPanel.setBorder(BorderFactory.createTitledBorder(null, "Secondary Components", TitledBorder.LEFT, TitledBorder.TOP, new Font("Segoe UI", 1, 14))); // NOI18N
        secondaryPanel.setFont(new Font("Segoe UI", 0, 12)); // NOI18N
        secondaryPanel.setMinimumSize(new Dimension(200, 200));

        GroupLayout secondaryPanelLayout = new GroupLayout(secondaryPanel);
        secondaryPanel.setLayout(secondaryPanelLayout);
        secondaryPanelLayout.setHorizontalGroup(secondaryPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        secondaryPanelLayout.setVerticalGroup(secondaryPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        clearConfigItem.setText("Clear configuration");
        fileMenu.add(clearConfigItem);

        importConfigItem.setText("Import from file");
        fileMenu.add(importConfigItem);

        saveConfigItem.setText("Save to file");
        fileMenu.add(saveConfigItem);
        fileMenu.add(jSeparator1);

        exitConfigItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0));
        exitConfigItem.setText("Exit configurator");
        fileMenu.add(exitConfigItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        helpItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0));
        helpItem.setText("Help");
        helpMenu.add(helpItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(controlPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(extensionsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(architecturePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(secondaryPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(primaryPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(architecturePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(primaryPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(extensionsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondaryPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void launchButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_launchButtonActionPerformed
        new OcelotEmulatorFrame().setVisible(true);
    }//GEN-LAST:event_launchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel architecturePanel;
    private JButton cancelButton;
    private JMenuItem clearConfigItem;
    private JPanel controlPanel;
    private JRadioButton customEEPROMButton;
    private JTextField customEEPROMField;
    private ButtonGroup eepromButtons;
    private JPanel eepromPanel;
    private JMenuItem exitConfigItem;
    private JPanel extensionsPanel;
    private JMenu fileMenu;
    private JMenuItem helpItem;
    private JMenu helpMenu;
    private JMenuItem importConfigItem;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JMenuBar jMenuBar1;
    private JPopupMenu.Separator jSeparator1;
    private JButton launchButton;
    private JRadioButton luaEEPROMButton;
    private JPanel primaryPanel;
    private JMenuItem saveConfigItem;
    private JPanel secondaryPanel;
    // End of variables declaration//GEN-END:variables
}
