/*
 * The MIT License
 *
 * Copyright 2020 Vladislav Gorskii.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package ru.VladTheMountain.ocide;

/**
 * OCIDE is an Integrated Development Environment, made specifically for
 * creating programs and libraries in Lua 5.2 or Lua 5.3 for OpenComputers 1.7.5
 *
 * Written in Java 8 using Swing GUI Library and Apache NetBeans 12.0
 *
 * @author VladTheMountain
 */
public class MainForm extends javax.swing.JFrame {

    /* Variables declaration */
    //Directories
    private final String APP_DIRECTORY = new java.io.File("").getAbsolutePath();
    private final String PROJECTS_DIR = APP_DIRECTORY + "/projects/";
    private final String OPENOS_SDK_DIR = APP_DIRECTORY + "/SDK/OpenOS/";
    //Workspace variables
    private java.io.File ACTIVE_FILE;
    private String ACTIVE_PROJECT;
    //Project types
    private final int OPENOS_PROG = 1,
            OPENOS_LIB = 2,
            CUSTOM = 3;

    /**
     * App constructor. Used for variable initialization
     */
    public MainForm() {
        ACTIVE_PROJECT = new java.io.File(PROJECTS_DIR).list()[0];
        ACTIVE_FILE = new java.io.File(PROJECTS_DIR + ACTIVE_PROJECT + "/main.lua");
        initComponents();
        new javax.swing.Timer(300, (java.awt.event.ActionEvent e) -> {
            this.repaint();
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, "Repainted");
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Apache NetBeans Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileDialog = new javax.swing.JFileChooser();
        createProjectDialog = new javax.swing.JDialog();
        navigationPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        buttons = new javax.swing.JPanel();
        finishButton = new javax.swing.JButton();
        nextStepButton = new javax.swing.JButton();
        previousStepButton = new javax.swing.JButton();
        cancelProjectCreation = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        projectName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        projectType = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        mainFile = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        projectLocation = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        openProjectDialog = new javax.swing.JDialog();
        topMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newProject = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        openProject = new javax.swing.JMenuItem();
        openFile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        saveProject = new javax.swing.JMenuItem();
        saveFile = new javax.swing.JMenuItem();
        exportProject = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        exitIDE = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoItem = new javax.swing.JMenuItem();
        redoItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        viewProjects = new javax.swing.JCheckBoxMenuItem();
        viewFiles = new javax.swing.JCheckBoxMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        viewNavigator = new javax.swing.JCheckBoxMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        viewOutput = new javax.swing.JCheckBoxMenuItem();
        runMenu = new javax.swing.JMenu();
        launchBasicTest = new javax.swing.JMenuItem();
        launchCustomConfigTest = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        libraries = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        modules = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        settings = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpItem = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        aboutItem = new javax.swing.JMenuItem();

        openFileDialog.setName("openFileDialog"); // NOI18N

        createProjectDialog.setTitle("Creating a new project...");
        createProjectDialog.setBounds(new java.awt.Rectangle(0, 0, 600, 300));
        createProjectDialog.setName("createProjectDialog"); // NOI18N
        createProjectDialog.setResizable(false);

        navigationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        navigationPanel.setName("navigationPanel"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("OpenComputers IDE");
        jLabel22.setToolTipText("");
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel24.setText("Created by VladG24");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setText("Version 1.0.0");
        jLabel25.setName("jLabel25"); // NOI18N

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(navigationPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel25))
                            .addComponent(jLabel24))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addGap(79, 79, 79))
        );

        buttons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buttons.setName("buttons"); // NOI18N

        finishButton.setText("Finish");
        finishButton.setName("finishButton"); // NOI18N
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        nextStepButton.setText("Next >>");
        nextStepButton.setEnabled(false);
        nextStepButton.setName("nextStepButton"); // NOI18N

        previousStepButton.setText("<< Previous");
        previousStepButton.setEnabled(false);
        previousStepButton.setName("previousStepButton"); // NOI18N
        previousStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousStepButtonActionPerformed(evt);
            }
        });

        cancelProjectCreation.setText("Cancel");
        cancelProjectCreation.setName("cancelProjectCreation"); // NOI18N
        cancelProjectCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelProjectCreationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsLayout = new javax.swing.GroupLayout(buttons);
        buttons.setLayout(buttonsLayout);
        buttonsLayout.setHorizontalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelProjectCreation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previousStepButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextStepButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton)
                .addContainerGap())
        );
        buttonsLayout.setVerticalGroup(
            buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(nextStepButton)
                    .addComponent(previousStepButton)
                    .addComponent(cancelProjectCreation))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Creating a project", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N

        jLabel1.setText("Project Name");
        jLabel1.setName("jLabel1"); // NOI18N

        projectName.setText("Example Project");
        projectName.setName("projectName"); // NOI18N
        projectName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                projectNameCaretUpdate(evt);
            }
        });

        jLabel4.setText("Project Type");
        jLabel4.setName("jLabel4"); // NOI18N

        projectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lua OpenComputers program", "Lua OpenComputers library", "Lua OpenComputers custom" }));
        projectType.setName("projectType"); // NOI18N

        jLabel10.setText("Main File");
        jLabel10.setName("jLabel10"); // NOI18N

        mainFile.setEditable(false);
        mainFile.setText(new java.io.File(PROJECTS_DIR).getPath() + "\\" + projectName.getText() + "\\main.lua");
            mainFile.setName("mainFile"); // NOI18N

            jLabel21.setText("Project Location");
            jLabel21.setName("jLabel21"); // NOI18N

            projectLocation.setText(new java.io.File(PROJECTS_DIR).getPath() + "\\" + projectName.getText());
                projectLocation.setName("projectLocation"); // NOI18N
                projectLocation.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        projectLocationActionPerformed(evt);
                    }
                });

                jSeparator8.setName("jSeparator8"); // NOI18N

                javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
                mainPanel.setLayout(mainPanelLayout);
                mainPanelLayout.setHorizontalGroup(
                    mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(mainFile, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel21))
                                        .addGap(18, 18, 18)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(projectName)
                                            .addComponent(projectType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(projectLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                mainPanelLayout.setVerticalGroup(
                    mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(projectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(projectType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(projectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(mainFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(65, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout createProjectDialogLayout = new javax.swing.GroupLayout(createProjectDialog.getContentPane());
                createProjectDialog.getContentPane().setLayout(createProjectDialogLayout);
                createProjectDialogLayout.setHorizontalGroup(
                    createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createProjectDialogLayout.createSequentialGroup()
                        .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                createProjectDialogLayout.setVerticalGroup(
                    createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createProjectDialogLayout.createSequentialGroup()
                        .addGroup(createProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                createProjectDialog.pack();

                openProjectDialog.setName("openProjectDialog"); // NOI18N

                javax.swing.GroupLayout openProjectDialogLayout = new javax.swing.GroupLayout(openProjectDialog.getContentPane());
                openProjectDialog.getContentPane().setLayout(openProjectDialogLayout);
                openProjectDialogLayout.setHorizontalGroup(
                    openProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 400, Short.MAX_VALUE)
                );
                openProjectDialogLayout.setVerticalGroup(
                    openProjectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 300, Short.MAX_VALUE)
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("OpenComputers IDE 1.0");
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                setLocation(new java.awt.Point(0, 0));
                setSize(getPreferredSize());

                topMenu.setName("topMenu"); // NOI18N

                fileMenu.setText("File");
                fileMenu.setName("fileMenu"); // NOI18N

                newProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                newProject.setText("New Project...");
                newProject.setName("newProject"); // NOI18N
                newProject.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        newProjectActionPerformed(evt);
                    }
                });
                fileMenu.add(newProject);

                jSeparator1.setName("jSeparator1"); // NOI18N
                fileMenu.add(jSeparator1);

                openProject.setText("Open Project...");
                openProject.setName("openProject"); // NOI18N
                openProject.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        openProjectActionPerformed(evt);
                    }
                });
                fileMenu.add(openProject);

                openFile.setText("Open File...");
                openFile.setName("openFile"); // NOI18N
                fileMenu.add(openFile);

                jSeparator2.setName("jSeparator2"); // NOI18N
                fileMenu.add(jSeparator2);

                saveProject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                saveProject.setText("Save Project");
                saveProject.setName("saveProject"); // NOI18N
                fileMenu.add(saveProject);

                saveFile.setText("Save File As...");
                saveFile.setName("saveFile"); // NOI18N
                fileMenu.add(saveFile);

                exportProject.setText("Export Project...");
                exportProject.setName("exportProject"); // NOI18N
                fileMenu.add(exportProject);

                jSeparator5.setName("jSeparator5"); // NOI18N
                fileMenu.add(jSeparator5);

                exitIDE.setText("Exit");
                exitIDE.setName("exitIDE"); // NOI18N
                fileMenu.add(exitIDE);

                topMenu.add(fileMenu);

                editMenu.setText("Edit");
                editMenu.setName("editMenu"); // NOI18N

                undoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                undoItem.setText("Undo");
                undoItem.setName("undoItem"); // NOI18N
                editMenu.add(undoItem);

                redoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                redoItem.setText("Redo");
                redoItem.setName("redoItem"); // NOI18N
                editMenu.add(redoItem);

                topMenu.add(editMenu);

                viewMenu.setText("View");
                viewMenu.setName("viewMenu"); // NOI18N

                viewProjects.setSelected(true);
                viewProjects.setText("Projects");
                viewProjects.setName("viewProjects"); // NOI18N
                viewMenu.add(viewProjects);

                viewFiles.setSelected(true);
                viewFiles.setText("Files");
                viewFiles.setName("viewFiles"); // NOI18N
                viewMenu.add(viewFiles);

                jSeparator6.setName("jSeparator6"); // NOI18N
                viewMenu.add(jSeparator6);

                viewNavigator.setSelected(true);
                viewNavigator.setText("Navigator");
                viewNavigator.setName("viewNavigator"); // NOI18N
                viewMenu.add(viewNavigator);

                jSeparator7.setName("jSeparator7"); // NOI18N
                viewMenu.add(jSeparator7);

                viewOutput.setSelected(true);
                viewOutput.setText("Output");
                viewOutput.setName("viewOutput"); // NOI18N
                viewMenu.add(viewOutput);

                topMenu.add(viewMenu);

                runMenu.setText("Test");
                runMenu.setName("runMenu"); // NOI18N

                launchBasicTest.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
                launchBasicTest.setText("Test on basic configurations");
                launchBasicTest.setName("launchBasicTest"); // NOI18N
                launchBasicTest.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        launchBasicTestActionPerformed(evt);
                    }
                });
                runMenu.add(launchBasicTest);

                launchCustomConfigTest.setText("Test on custom configuration...");
                launchCustomConfigTest.setName("launchCustomConfigTest"); // NOI18N
                runMenu.add(launchCustomConfigTest);

                topMenu.add(runMenu);

                toolsMenu.setText("Tools");
                toolsMenu.setName("toolsMenu"); // NOI18N

                libraries.setText("Libraries");
                libraries.setName("libraries"); // NOI18N
                toolsMenu.add(libraries);

                jSeparator3.setName("jSeparator3"); // NOI18N
                toolsMenu.add(jSeparator3);

                modules.setText("Modules");
                modules.setName("modules"); // NOI18N
                toolsMenu.add(modules);

                jSeparator4.setName("jSeparator4"); // NOI18N
                toolsMenu.add(jSeparator4);

                settings.setText("Settings");
                settings.setName("settings"); // NOI18N
                settings.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        settingsActionPerformed(evt);
                    }
                });
                toolsMenu.add(settings);

                topMenu.add(toolsMenu);

                helpMenu.setText("Help");
                helpMenu.setName("helpMenu"); // NOI18N

                helpItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
                helpItem.setText("Help");
                helpItem.setName("helpItem"); // NOI18N
                helpItem.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        helpItemActionPerformed(evt);
                    }
                });
                helpMenu.add(helpItem);

                jSeparator9.setName("jSeparator9"); // NOI18N
                helpMenu.add(jSeparator9);

                aboutItem.setText("About");
                aboutItem.setName("aboutItem"); // NOI18N
                aboutItem.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        aboutItemActionPerformed(evt);
                    }
                });
                helpMenu.add(aboutItem);

                topMenu.add(helpMenu);

                setJMenuBar(topMenu);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 339, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 578, Short.MAX_VALUE)
                );

                getAccessibleContext().setAccessibleDescription("Yee");

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectActionPerformed
        createProjectDialog.setVisible(true);
    }//GEN-LAST:event_newProjectActionPerformed

    private void launchBasicTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchBasicTestActionPerformed

    }//GEN-LAST:event_launchBasicTestActionPerformed

    private void helpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpItemActionPerformed

    }//GEN-LAST:event_helpItemActionPerformed

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed

    }//GEN-LAST:event_aboutItemActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed

    }//GEN-LAST:event_settingsActionPerformed

    private void projectNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_projectNameCaretUpdate
        projectLocation.setText(new java.io.File(PROJECTS_DIR).getPath() + "/" + projectName.getText());
        mainFile.setText(new java.io.File(PROJECTS_DIR).getPath() + "/" + projectName.getText() + "/main.lua");
    }//GEN-LAST:event_projectNameCaretUpdate

    private void openProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectActionPerformed
        openProjectDialog.setVisible(true);
    }//GEN-LAST:event_openProjectActionPerformed

    private void projectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectLocationActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        java.io.File projectMainFile = new java.io.File(mainFile.getText());
        try {
            new java.io.File(projectLocation.getText()).mkdirs();
            projectMainFile.createNewFile();
        } catch (java.io.IOException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        createProjectDialog.dispose();
    }//GEN-LAST:event_finishButtonActionPerformed

    private void cancelProjectCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelProjectCreationActionPerformed
        createProjectDialog.dispose();
    }//GEN-LAST:event_cancelProjectCreationActionPerformed

    private void previousStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousStepButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousStepButtonActionPerformed

    /**
     * Main method. The program's starting point
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //L&F setting
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex
            );
        }
        //
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
        new ru.VladTheMountain.ocide.validator.ValidatorFrame().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenuItem aboutItem;
    javax.swing.JPanel buttons;
    javax.swing.JButton cancelProjectCreation;
    javax.swing.JDialog createProjectDialog;
    javax.swing.JMenu editMenu;
    javax.swing.JMenuItem exitIDE;
    javax.swing.JMenuItem exportProject;
    javax.swing.JMenu fileMenu;
    javax.swing.JButton finishButton;
    javax.swing.JMenuItem helpItem;
    javax.swing.JMenu helpMenu;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel21;
    javax.swing.JLabel jLabel22;
    javax.swing.JLabel jLabel24;
    javax.swing.JLabel jLabel25;
    javax.swing.JLabel jLabel4;
    javax.swing.JPopupMenu.Separator jSeparator1;
    javax.swing.JPopupMenu.Separator jSeparator2;
    javax.swing.JPopupMenu.Separator jSeparator3;
    javax.swing.JPopupMenu.Separator jSeparator4;
    javax.swing.JPopupMenu.Separator jSeparator5;
    javax.swing.JPopupMenu.Separator jSeparator6;
    javax.swing.JPopupMenu.Separator jSeparator7;
    javax.swing.JSeparator jSeparator8;
    javax.swing.JPopupMenu.Separator jSeparator9;
    javax.swing.JMenuItem launchBasicTest;
    javax.swing.JMenuItem launchCustomConfigTest;
    javax.swing.JMenuItem libraries;
    javax.swing.JTextField mainFile;
    javax.swing.JPanel mainPanel;
    javax.swing.JMenuItem modules;
    javax.swing.JPanel navigationPanel;
    javax.swing.JMenuItem newProject;
    javax.swing.JButton nextStepButton;
    javax.swing.JMenuItem openFile;
    javax.swing.JFileChooser openFileDialog;
    javax.swing.JMenuItem openProject;
    javax.swing.JDialog openProjectDialog;
    javax.swing.JButton previousStepButton;
    javax.swing.JTextField projectLocation;
    javax.swing.JTextField projectName;
    javax.swing.JComboBox<String> projectType;
    javax.swing.JMenuItem redoItem;
    javax.swing.JMenu runMenu;
    javax.swing.JMenuItem saveFile;
    javax.swing.JMenuItem saveProject;
    javax.swing.JMenuItem settings;
    javax.swing.JMenu toolsMenu;
    javax.swing.JMenuBar topMenu;
    javax.swing.JMenuItem undoItem;
    javax.swing.JCheckBoxMenuItem viewFiles;
    javax.swing.JMenu viewMenu;
    javax.swing.JCheckBoxMenuItem viewNavigator;
    javax.swing.JCheckBoxMenuItem viewOutput;
    javax.swing.JCheckBoxMenuItem viewProjects;
    // End of variables declaration//GEN-END:variables

    /* End of program's code */
}
